# Generated by Django 3.2.11 on 2022-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
